### Raiz da aplicação
GET http://localhost:5081/

### Testar a segunda funcionalidade
GET  http://localhost:5081/api/produto/listar

### Buscar produto por nome
GET  http://localhost:5081/api/produto/buscar/TV
###Cadastrar produto 
POST http://localhost:5081/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "TV",
    "quntidade" : 324,
    "preco" : 678.89
}

### Remover produto por id
DELETE http://localhost:5081/api/produto/excluir/395209d9-38e0-49a8-b5ce-7896c13c8187

###
PATCH http://localhost:5081/api/produto/alterar/f2a96e81-0ee9-45b2-94ec-a342c4bb981d
Content-Type: application/json

{
    "nome" : "TV",
    "quntidade" : 324,
    "preco" : 678.89
}
